# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
   branches:
     include:
       - master
pool:
  vmImage: windows-2019
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  inputs:
    targetType: filePath
    pwsh: false
    filePath: .\Build-Pipeline.ps1
    arguments: $(PSNugetApiKey)
      

