# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
   branches:
     include:
       - master
pool:
  name: Self
steps:
- checkout: self
  clean: true
- task: PowerShell@2
  inputs:
    targetType: filePath
    pwsh: true
    filePath: .\Build-Pipeline.ps1
    arguments: $(PSNugetApiKey)
      

